# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 17:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_auto_20170424_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='match',
            new_name='matches',
        ),
    ]
