# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_player_battle_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='battle_tag',
            field=models.CharField(default='#nameXXXX', max_length=256, unique=True),
        ),
    ]
