# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_auto_20170426_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='tournaments',
            field=models.ManyToManyField(blank=True, related_name='tournament_players', to='tournament.Tournament'),
        ),
    ]
