# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-29 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0008_auto_20170426_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
